default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: mbos_development
  username: mbos

test:
  <<: *default
  database: mbos_test

production:
  <<: *default
  database: mbos_production
  username: mbos
  password: <%= ENV['MBOS_DATABASE_PASSWORD'] %>
